# # Packages
brew 'python3'
brew 'ack'
brew 'tree'
brew 'wget'
brew 'vim'
brew 'git'
brew 'hub'
brew 'tmux'
brew 'zsh'
brew 'nvm'
brew 'markdown'
brew 'graphviz'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'
brew 'awscli'
brew 'watch'
brew 'reattach-to-user-namespace'
brew 'coreutils'
brew 'htop-osx'
brew 'cmake'
brew 'ccache'
brew 'android-sdk'
brew 'android-ndk'


# Casks
cask_args appdir: '/Applications'
tap 'caskroom/cask'
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'quicklook-csv'
cask 'betterzipql'
cask 'google-chrome'
cask 'iterm2'
cask 'virtualbox'
cask 'spotify'
cask 'flux'
cask 'alfred'
cask 'hammerspoon'
cask 'caskroom/versions/firefoxdeveloperedition'
cask 'ccmenu'
cask 'electron'
cask 'firefox'
cask 'istat-menus'
cask 'iterm2'
cask 'osxfuse'
cask 'skype'
cask 'vlc'
cask 'microsoft-office'
cask 'bartender'
cask 'mysqlworkbench'
cask 'karabiner-elements'
cask 'visual-studio-code'
cask 'adobe-creative-cloud'
cask 'skyfonts'
cask 'telegram'
cask 'android-studio'
cask 'docker'

# Fonts
cask 'font-sourcecodepro-nerd-font'

# App Store Apps
brew 'mas'
mas 'OmniGraffle', id: 1142578753
mas 'Textual', id: 896450579
mas 'Airmail 3', id: 918858936
mas 'Xcode', id: 497799835
mas 'Pocket', id: 568494494
mas 'iA Writer', id: 775737590
mas 'Slack', id: 803453959
mas 'Fantastical 2', id: 975937182
mas 'LastPass', id: 926036361
mas 'Tweetbot', id: 557168941
