# # Packages
brew 'python3'
brew 'ack'
brew 'tree'
brew 'wget'
brew 'vim'
brew 'git'
brew 'hub'
brew 'tmux'
brew 'zsh'
brew 'nvm'
brew 'markdown'
brew 'graphviz'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'
brew 'awscli'
brew 'watch'
brew 'reattach-to-user-namespace'
brew 'coreutils'
brew 'htop-osx'
brew 'cmake'
brew 'ccache'

# Casks
cask_args appdir: '/Applications'
tap 'caskroom/cask'
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'google-chrome'
cask 'iterm2'
cask 'spotify'
cask 'alfred'
cask 'hammerspoon'
cask 'ccmenu'
cask 'android-sdk'
cask 'android-ndk'
cask 'istat-menus'
cask 'iterm2'
cask 'vlc'
cask 'bartender'
cask 'karabiner-elements'
cask 'visual-studio-code'
cask 'hyper'
cask 'skyfonts'
cask 'telegram'
cask 'android-studio'
cask 'docker'
cask 'vivaldi'
cask 'sketch'

# Drivers
cask 'logitech-gaming-software'
cask 'logitech-options'
cask 'hp-easy-start'

# Fonts
cask 'font-fira-code'

# App Store Apps
brew 'mas'
mas 'OmniGraffle', id: 1142578753
mas 'Xcode', id: 497799835
mas 'iA Writer', id: 775737590
mas 'Slack', id: 803453959
mas 'Fantastical 2', id: 975937182
mas '1Password', id: 1333542190
